global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb_exporter:9216']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']